services:

  db:
    image: mysql
    container_name: mysql-db
    restart: always
    ports:
      - '3307:3306'
    environment:   
      MYSQL_ROOT_PASSWORD: root   
    networks:
      - app-tier1

  spring_boot:
    build:
      context: .
      dockerfile: ./Dockerfile  
    restart: always
    ports:
      - '8081:8080'
    depends_on:
      - db
      - elasticsearch
      - logstash
    networks:
      - app-tier1  
  elasticsearch:
    image: elasticsearch:6.8.20
    networks:
      - app-tier1    
    ports:
      - "9201:9200"
  logstash:
    image: logstash:6.8.20
    networks:
      - app-tier1    
    depends_on:
        - elasticsearch
    ports:
      - "5000:5000"
  kibana:
    image: kibana:6.8.20
    networks:
      - app-tier1    
    depends_on:
        - elasticsearch
    ports:
      - "5602:5601"
networks:
  app-tier1:
    driver: bridge